# 1. Numpy数组的属性
    每个数组有 nidm（数组的维度） 、 shape（数组每个维度的大小） 、size（数组的总大小） 属性、数组数据类型、数组每个数组元素字节大小的itemsize以及表示数组总字节大小的属性nbytes

In [8]:
import numpy as np
np.random.seed(0)  # 设置随机种子，此后产生的随机数都会被记住

x3 = np.random.randint(10, size=(3, 4, 5)) # 三维数组
print("x3 ndim: ", x3.ndim)  # 获取维度
print("x3 shape: ", x3.shape)  # 获取每个维度的大小
print("x3 size: ", x3.size)  # 获取数组的总大小
print("x3 itemsize: ", x3.itemsize, "bytes") # 获取每个元素的字节大小
print("x3 nbytes: ", x3.nbytes, "bytes") # 获取数组的所有元素字节大小，并不是数组的总大小

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60
x3 itemsize:  4 bytes
x3 nbytes:  240 bytes


    一般来说，可以认为nbytes = itemsize * size

# 2. 数组索引
    Numpy的索引方式与Python列表一样，但有一点需要注意，Numpy数组是固定类型的。这意味着你试图将一个浮点型值插入一个整型数组时，浮点值会被截断成整型。并且这种截断是自动完成的，不会给你提示或警告。

In [13]:
x = np.array([1,2,3,4,5,6,7,8,9], dtype="int32")
x[0] = 3.14159  # 想将float数据插入numpy的int数组,但最终发现插入的是被截取后的整型值
x

array([3, 2, 3, 4, 5, 6, 7, 8, 9])

# 3. 数组切片
    Numpy切片语法与Python列表的标准切片语法相同。为了获取数组 x 的一个切片，可以用以下方式：
    x[start:stop:step] 
    如果以上三个参数都未指定，那么会被分别设置默认值start=0、stop=维度大小、step=1.

In [16]:
x = np.arange(10)  # 创建一个含有10个元素的整型数组，元素值为[0,10)
print("x = ", x)
print("x[::2] = ", x[::2])  # 从头到尾且每隔一个元素
print("x[1::2] = ", x[1::2])  # 第二个元素到末尾且每隔一个元素

x =  [0 1 2 3 4 5 6 7 8 9]
x[::2] =  [0 2 4 6 8]
x[1::2] =  [1 3 5 7 9]


    当步长值为负值是，start参数和stop参数默认是被交换的。

In [17]:
x = np.arange(10)  # 创建一个含有10个元素的整型数组，元素值为[0,10)
print("x = ", x)
print("x[::-1] = ", x[::-1])  # 所有元素，倒序(逆序)
print("x[::-2] = ", x[::-2])  # 所有元素，倒序(逆序)，每隔一个元素

x =  [0 1 2 3 4 5 6 7 8 9]
x[::-1] =  [9 8 7 6 5 4 3 2 1 0]
x[::-2] =  [9 7 5 3 1]


# 4. 数组的变形
    数组变形最灵活的实现方式是通过reshape()函数来实现。

In [21]:
x = np.arange(12)
print("x = ", x)
print("x.shape = ", x.shape)
x = x.reshape((3, 4)) # 把一行12列的数组变成3行4列的数组
print("x = ", x)
print("x.shape = ", x.shape)

x =  [ 0  1  2  3  4  5  6  7  8  9 10 11]
x.shape =  (12,)
x =  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
x.shape =  (3, 4)


    另外一个常见的变形模式是将一个一维数组转变为二维的行或列的矩阵。可以通过reshape的方式实现，获取在一个切片操作中利用newaxis关键字（相当于增加一个维度）实现：

In [28]:
x = np.array([1,2,3,4,5,6,7,8,9,10])
print(x.reshape(1, -1))  # 复数表示自适应，根据size自动规划shape
print(x[np.newaxis, :])
print(x.reshape(2,5))  # 把1行10列的数组变成2行5列的数组
print(x[:, np.newaxis])

[[ 1  2  3  4  5  6  7  8  9 10]]
[[ 1  2  3  4  5  6  7  8  9 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]


# 5. 数组拼接和分裂
## 5.1 数组的拼接
    拼接或连接Numpy中的两个数组主要由np.concatenate、np.vstack 和 np.hstack 实现。

In [44]:
x = np.array([1,2,3,4,5])
y = np.array([6,7,8,9,10])
print(np.concatenate([x, y]))  # np.concatenate 将数组元组或数组列表作为第一个参数
z = np.array([11, 12, 13, 14 ,15])
print(np.concatenate([x, y, z]))
print("=" * 10)
# np.concatenate 也可用于二维数组拼接
x1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(x1)
print("x1.shape = ", x1.shape)
print(np.concatenate([x1, x1]))  # 默认为纵向拼接
print("np.concatenate([x1, x1]).shape = ", np.concatenate([x1, x1]).shape)
print(np.concatenate([x1, x1], axis=1))  # 横向拼接
print("np.concatenate([x1, x1], axis=1).shape = ", np.concatenate([x1, x1], axis=1).shape)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
x1.shape =  (2, 5)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]
 [ 6  7  8  9 10]]
np.concatenate([x1, x1]).shape =  (4, 5)
[[ 1  2  3  4  5  1  2  3  4  5]
 [ 6  7  8  9 10  6  7  8  9 10]]
np.concatenate([x1, x1], axis=1).shape =  (2, 10)


    沿着固定维度处理数据时，使用np.vstack（垂直栈）和 np.hstack（水平栈）函数会更简洁

In [50]:
x = np.array([1,2,3])
grid = np.array([[9,8,7], [6,5,4]])

# 垂直栈数组
print(np.vstack([x, grid]))
print("=" * 20)
y = np.array([[1,2,3], [1,2,3]])
# 水平栈数组
print(np.hstack([y, grid]))

[[1 2 3]
 [9 8 7]
 [6 5 4]]
[[1 2 3 9 8 7]
 [1 2 3 6 5 4]]


    与之类似，np.dstack 将沿着第三个维度拼接

In [57]:
x = np.array([[[1,2,3],[1,2,3]],[[4,5,6], [4,5,6]]])
print(x)
print("x.shape = {}".format(x.shape))
print("=" * 20)

z = np.array([[[7,8,9],[7,8,9]],[[10, 11, 12], [10, 11, 12]]])
np.dstack([x, z])

[[[1 2 3]
  [1 2 3]]

 [[4 5 6]
  [4 5 6]]]
x.shape = (2, 2, 3)


array([[[ 1,  2,  3,  7,  8,  9],
        [ 1,  2,  3,  7,  8,  9]],

       [[ 4,  5,  6, 10, 11, 12],
        [ 4,  5,  6, 10, 11, 12]]])

## 5.2 数组的分裂
    分裂可以通过 np.spalit、 np.hsplit 和 np.vsplit 函数来实现。可以向以上函数传递一个索引列表作为参数,索引列表记录的时分裂点位置：

In [59]:
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print(np.split(x, [3,5]))

[array([1, 2, 3]), array([4, 5]), array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])]


    值得注意的时，N个分裂点会得到N+1个子数组。相关的np.hsplit 和 np.vsplit 的用法也类似：

In [62]:
grid = np.arange(16).reshape((4,4))
print(grid)
print("=" * 20)
x1, x2 = np.vsplit(grid, [2])
print(x1)
print()
print(x2)
print("=" * 20)
x1, x2 = np.hsplit(grid, [2])
print(x1)
print()
print(x2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1 2 3]
 [4 5 6 7]]

[[ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


    同样， np.dsplit将数组沿着第三个维度分裂

In [67]:
grid = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]])
print(grid)
print("=" * 20)

x1 ,x2 = np.dsplit(grid, [2])
print(x1)
print()
print(x2)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
[[[ 1  2]
  [ 6  7]]

 [[11 12]
  [16 17]]]

[[[ 3  4  5]
  [ 8  9 10]]

 [[13 14 15]
  [18 19 20]]]
